---
- name: Ensure osbuild repo directory exists
  ansible.builtin.file:
    path: /etc/osbuild-composer/repositories/
    state: directory
   
- name: Copy blueprint template packages are listed in defaults or add with -e blueprint_packages=<packagename>
  ansible.builtin.template:
    src: templates/blueprint.toml.j2
    dest: "/tmp/blueprint.toml"

- name: Push Blueprint to Server
  command: >
    composer-cli blueprints push /tmp/blueprint.toml

- name: Resolve Dependencies
  command: >
    composer-cli blueprints depsolve {{ blueprint_name }}

- name: Freeze Blueprint
  command: >
    composer-cli -j blueprints freeze {{ blueprint_name }}
  register: frozen_blueprint

# - name: Set Blueprint Version Number
#   set_fact:
#     blueprint_version: "{{ (frozen_blueprint.stdout | from_json).blueprints[0].blueprint.version }}"
