---
- name: Generate RFE Boot ISO Image
  become: yes
  hosts: builder
  tasks:
    # - name: Configure Content Sources
    #   ansible.builtin.include_role:
    #     name: image-builder-content-sources

    - name: Build Installer Image
      ansible.builtin.include_role:
        name: oci-build-installer-image
